### ISSUE TITLE
Vue2 warning: Invalid default value for prop "media"

### ISSUE THREAD

**Issue by zumm-l3ss** [saimow/vue-media-upload#16]
Good day,
I get the following errors in console: 

```
[Vue warn]: Invalid default value for prop "media": Props with type Object/Array must use a factory function to return the default value.

found in ---> <Uploader> at node_modules/vue-media-upload/src/Uploader.vue
```

It s there anything i m not doing fine?

Edit: I m using this on Vue2

**Comment by saimow** [comment]
I believe the reason for this issue is that you are using Vue2.
can I see how you are using the component.

**Comment by zumm-l3ss** [comment]
I m using it inside a vue component

`<Uploader
													server="/api/media/upload"
													@change="changeMedia"
													maxFilesize="15"
												/>`

**Comment by saimow** [comment]
Try passing an empty array to the `:media` prop, and see if you still get this warning.
```
<Uploader 
  :media="[]"
  server="/api/media/upload" 
  @change="changeMedia" 
  maxFilesize="15" 
/>
```

**Comment by zumm-l3ss** [comment]
Yep. I used it like you said, and working like a charm

Also, i should add :maxFilesize 

Now the code is : 
`<Uploader
													:media="[]"
													server="/api/produse/media/upload"
													@change="changeMedia"
													:maxFilesize="15"
												/>`

Working with no errors

Thanks alot !
