### ISSUE TITLE
Support to display images from a server

### ISSUE THREAD

**Issue by michaelnjuguna** [saimow/vue-media-upload#18]
When fetching images from a server and you need to display them through Upload-media tags there is no native support, could you implement that

**Comment by guifsdev** [comment]
I'm also on the same boat...

**Comment by Vahagn-99** [comment]
i achive that writing something like this <template>
  <div class="mx-auto max-w-7xl py-6 sm:px-6 lg:px-8">
    <form action="#" @submit.prevent="handleSave">
      <div class="grid gap-4 mb-4 sm:grid-cols-2">
        <Select
          v-if="isClientDevice || !device.is_new"
          :label="$t('alias.client')"
          :options="clients.data"
          optionKey="name"
          :selected="device.client?.id"
          selected-key="id"
          name="client_id"
          @update:value="handleClient"
          :errors="device.errors?.client_id"
        />
        <div class="flex justify-between gap-2 items-end">
          <Select
            :label="$t('alias.brand')"
            name="brand"
            @update:value="handleBrand"
            :options="brands"
            optionKey="name"
            :selected="device.brand?.id"
            selected-key="id"
            :errors="device.errors?.brand_id"
          />
          <ActionButton
            label="add brand"
            action="create"
            @action:click="addBrand"
          />
        </div>
        <div class="flex justify-between gap-2 items-end">
          <Select
            :disabled="disableModelSelect"
            :label="$t('alias.model')"
            name="model"
            @update:value="handleModel"
            :options="models"
            optionKey="name"
            :selected="device.model?.id"
            selected-key="id"
            :errors="device.errors?.model_id"
          />
          <ActionButton
            label="add model"
            action="create"
            @action:click="addModel"
          />
        </div>
        <Select
          v-if="device.is_new"
          :label="$t('alias.supplier')"
          :options="suppliers.data"
          :selected="device.supplier?.id"
          optionKey="email"
          selected-key="id"
          name="supplier"
          @update:value="handleSupplier"
          :errors="device.errors?.supplier_id"
        />
        <Input
          :type="'text'"
          :label="$t('alias.additional_info')"
          :name="'additional_info'"
          :errors="device.errors?.additional_info"
          v-model="device.additional_info"
          :placeholder="'Jone'"
        />
        <Input
          type="number"
          :label="$t('alias.imei')"
          :name="'imei'"
          :errors="device.errors?.imei"
          v-model="device.imei"
          :placeholder="'0XXXXXXXXX'"
        />
        <Input
          type="number"
          :label="$t('alias.serial_number')"
          :name="'email'"
          :errors="device.errors?.serial_number"
          v-model="device.serial_number"
          :placeholder="'1212121212'"
        />
        <Input
          :type="'text'"
          :label="$t('alias.device_password')"
          :name="'device_password'"
          :errors="device.errors?.device_password"
          v-model="device.device_password"
          :placeholder="'my device'"
        />
        <Input
          :type="'text'"
          :label="$t('alias.screen_password')"
          :name="'screen_password'"
          :errors="device.errors?.screen_password"
          v-model="device.screen_password"
          :placeholder="'my device'"
        />
        <Input
          type="number"
          :label="$t('alias.cost')"
          :name="'cost'"
          :errors="device.errors?.cost"
          v-model="device.cost"
        />
        <div class="flex items-end justify-between">
          <Toggle
            @event:change="toggleDeviceClient"
            :label="$t('alias.is_new')"
            v-model="device.is_new"
          />
          <Toggle
            :label="$t('alias.temporary_device')"
            v-model="device.is_temporary"
          />
        </div>
        <label
          for="name"
          class="py-2 mb-1 text-sm font-medium text-gray-900 dark:text-white"
          ><span class="pb-5">Upload images</span>
          <Uploader
            :server="imagesServer"
            @add="addMedia"
            @remove="removeMedia"
            @change="changeMedia"
            :media="media"
            :location="imagesLocation"
          />
        </label>
      </div>
      <div class="flex items-center space-x-4">
        <button
          type="submit"
          class="text-white bg-primary-700 hover:bg-primary-800 focus:ring-4 focus:ring-primary-300 font-medium rounded-lg text-sm px-4 py-2 dark:bg-primary-600 dark:hover:bg-primary-700 focus:outline-none dark:focus:ring-primary-800"
        >
          {{ $t("crud.save") }}
        </button>
      </div>
      <div
        class="block mb-2 text-sm font-medium text-gray-900 dark:text-white mt-10"
      >
        * - mandatory
      </div>
    </form>
  </div>
  <Modal :size="size" v-if="isShowModal" @close="closeModal">
    <template #header>
      <div class="flex items-center text-lg">Add Brand</div>
    </template>
    <template #body>
      <form v-if="currentModalIs('brand')">
        <Input
          type="text"
          :label="$t('alias.brand_name')"
          name="name"
          :errors="brand.errors?.name"
          v-model="brand.name"
        />
      </form>
      <form v-if="currentModalIs('model')">
        <Select
          :label="$t('alias.brand')"
          name="brand"
          @update:value="handleBrand"
          :options="brands"
          optionKey="name"
          :selected="device.brand?.id"
          selected-key="id"
          :errors="model.errors?.brand_id"
        />

        <Input
          type="text"
          :label="$t('alias.model_name')"
          name="name"
          :errors="model.errors?.name"
          v-model="model.name"
        />
      </form>
    </template>
    <template #footer>
      <div class="flex justify-end">
        <button
          @click="closeModal"
          type="button"
          class="text-gray-500 bg-white hover:bg-gray-100 focus:ring-4 focus:outline-none focus:ring-primary-300 rounded-lg border border-gray-200 text-sm font-medium px-5 py-2.5"
        >
          Cancel
        </button>
        <button
          v-if="currentModalIs('brand')"
          @click="handleNewBrand"
          type="button"
          class="ml-2 text-white bg-primary-700 hover:bg-primary-800 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800"
        >
          Save
        </button>
        <button
          v-if="currentModalIs('model')"
          @click="handleNewModel"
          type="button"
          class="ml-2 text-white bg-primary-700 hover:bg-primary-800 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800"
        >
          Save
        </button>
      </div>
    </template>
  </Modal>
</template>

<script setup>
import { onMounted, ref } from "vue";
import Input from "@components/elements/Input.vue";
import Select from "@components/elements/Select.vue";
import { useDevice } from "@compositions/useDevice";
import { useSupplier } from "@compositions/useSupplier";
import { useClient } from "@compositions/useClient";
import { useBrand } from "@compositions/useBrand";
import { useModel } from "@compositions/useModel";
import Toggle from "@components/elements/Toggle.vue";
import ActionButton from "@components/elements/ActionButton.vue";
import { Modal } from "flowbite-vue";

const { saveDevice, device } = useDevice();
const { getSuppliers, suppliers } = useSupplier();
const { getClients, clients } = useClient();
const { getBrands, brands, saveBrand, brand } = useBrand();
const { models, getBrandModels, saveModel, model } = useModel();

const disableModelSelect = ref(device.value.brand_id <= 0);

const isShowModal = ref(false);

const imagesLocation =  import.meta.env.VITE_BACK_END_PROD + "/storage/images/devices";
const imagesServer = import.meta.env.VITE_BACK_END_API_PROD + "/upload/images";

const media = device.value?.images
  ? device.value.images.map((image) => {
      return {
        id: image.id,
        name: image.name,
      };
    })
  : [];

const currentModal = ref("brand");

function closeModal() {
  isShowModal.value = false;
}
function showModal() {
  isShowModal.value = true;
}

function addBrand() {
  currentModal.value = "brand";
  showModal();
}

function addModel() {
  currentModal.value = "model";
  showModal();
}

function currentModalIs(modal) {
  return modal === currentModal.value;
}

function toggleDeviceClient() {
  if (device.value.is_new) {
    device.value.client = {};
  } else {
    device.value.supplier = {};
  }
}

async function handleBrand(brandId) {
  device.value.brand_id = brandId;
  model.value.brand_id = brandId;
  await getBrandModels(brandId);
}

function handleModel(model_id) {
  device.value.model_id = model_id;
}

function handleClient(client_id) {
  device.value.client_id = client_id;
}
function handleSupplier(supplier_id) {
  device.value.supplier_id = supplier_id;
}

async function handleSave() {
  await saveDevice();
}

async function handleNewBrand() {
  await saveBrand();
  closeModal();
}

async function handleNewModel() {
  await saveModel();
  closeModal();
}

function removeMedia(image) {
  if (image.id) {
    if (device.value.remove_images === undefined) {
      device.value.remove_images = [];
    }
    device.value.remove_images.push(image);
  }
  const index = device.value.images.indexOf(image);
  device.value.images.splice(index, 1);
}

function addMedia(image) {
  if (device.value.images === undefined) {
    device.value.images = [];
  }
  device.value.images.push(image);
}

onMounted(async () => {
  await getClients();
  await getSuppliers();
  await getBrands();
  if (device.value.brand?.id) {
    await getBrandModels(device.value.brand?.id);
  }
});
</script>
 i provide whole component but if you want to find the answer, pleace see this code

**Comment by saimow** [comment]
After fetching the images you can pass them to the component to be displayed using the `media` prop.

```js
<Uploader
    :media="media"
/>
```
```js
data() {
    return {
        media: [{'name': '123_image.jpg'}, {'name': '456_image.jpg'}]
    }
}
```

Check this example: https://github.com/saimow/vue-media-upload?tab=readme-ov-file#update-form

Demo example: https://github.com/saimow/media-upload-demo/blob/main/resources/js/layouts/Posts/Update.vue
