### ISSUE TITLE
Using multiple times

### ISSUE THREAD

**Issue by GalBrigitta** [saimow/vue-media-upload#20]
I tried to use in a form multiple times but it does not work.
I would need it for example if a model has a basic photo and other media collections. Even if I want to upload at the second one, it appears at the first one
```
   <div class="row g-4 mt-1">
          <Uploader server="/store-media" @change="changeBasicMedia"/>
        </div>
        <div class="row g-4 mt-1">
          <Uploader server="/store-media" @change="changeMediaCollection"/>
        </div>
```
```
const basicMedia = ref();
const mediaCollection = ref([]);

const changeBasicMedia = (basic) => {
  basicMedia.value = basic;
};

const changeMediaCollection = (collection) => {
  mediaCollection.value = collection;
};
```

**Comment by lutuh** [comment]
@GalBrigitta Thank you very much for your Pull Request! I was stuck on using multiple instances of the uploader and you gave me the hint into the right direction.

@saimow Please consider a merge. Thank you!
